server:
  port: 8080
  
spring:
  banner:
    location: classpath:banner/banner.txt
  datasource:
    url: jdbc:mysql://localhost:3306/udemy?useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Parsertest1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5Dialect
    
logging:  level:    org.hibernate.SQLQuery: debug